name: Build BT Scanner

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build with Docker
      run: |
        # Создаем правильную структуру
        mkdir -p applications_user/bt_scanner
        cp -r bt_scanner/* applications_user/bt_scanner/
        
        echo "=== Files before build ==="
        ls -la applications_user/bt_scanner/
        
        # Компилируем в Docker
        docker run --rm -v $(pwd):/work -w /work \
          flipperdevices/flipperzero-toolchain:latest \
          ./fbt fap_bt_scanner
          
        echo "=== Searching for built files ==="
        find . -name "*.fap" -type f 2>/dev/null || echo "No .fap files found"
        find . -name "bt_scanner*" -type f 2>/dev/null | head -10
        
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: build-results
        path: |
          build/
          applications_user/
