name: Build BT Scanner

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build with Docker
      run: |
        # Клонируем прошивку
        git clone https://github.com/flipperdevices/flipperzero-firmware.git
        cd flipperzero-firmware
        
        # Копируем наше приложение
        mkdir -p applications_user/bt_scanner
        cp -r ../bt_scanner/* applications_user/bt_scanner/
        
        echo "=== Files structure ==="
        ls -la applications_user/bt_scanner/
        
        # Компилируем
        ./fbt fap_bt_scanner
        
        echo "=== Build results ==="
        find . -name "bt_scanner.fap" -type f
        
    - name: Upload FAP
      uses: actions/upload-artifact@v4
      with:
        name: bt-scanner
        path: flipperzero-firmware/build/f7-firmware-D/.extapps/bt_scanner.fap
